import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "./providers";
import "./globals.css";

const suit = localFont({
  src: "./fonts/SUIT-Variable.woff2",
  variable: "--font-suit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suit.variable} antialiased max-w-[480px] mx-auto h-dvh overflow-y-hidden`}
      >
        <div className="w-full h-full bg-gray-100 overflow-y-auto">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
